### ISSUE TITLE
系统找不到指定文件

### ISSUE THREAD

**Issue by LaBiXiaoChen** [DuanJiaNing/Decompile#1]
您好，我近期在学习使用你的Decompile Public项目的时候，发现了一个无法解决的错误，希望能得到你的帮助。
我在做完所有步骤的时候，发现java总是报一个错误，并且我下载导入了一个恶意的apk文件，发现还是会报错
报错如下：
![image](https://user-images.githubusercontent.com/74575814/160962492-f1e1714e-eecf-4070-bbce-c7217ae44141.png)
系统环境：windows10
java版本：
![image](https://user-images.githubusercontent.com/74575814/160962773-cd0e1152-05e2-42ef-a248-0283267b1092.png)
我已给您写信了，十分感谢，希望能得到您的解答！

**Comment by DuanJiaNing** [comment]
下载 [apktool.bat](https://ibotpeaches.github.io/Apktool/install/) 并放入 D:\Decompile\tools\apktool\ 文件夹内，再运行程序。

**Comment by LaBiXiaoChen** [comment]
十分感谢大佬，回复速度超级快，十分感谢
